name: Coding Standards

on:
  pull_request:
    paths:
      - "**.php"
      - "**.phtml"

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version
          git clone --depth 1 --branch v6 https://github.com/magento/magento-coding-standard.git
      - uses: tinovyatkin/action-php-codesniffer@v1
        with:
          files: "**"
          scope: files
          phpcs_path: php phpcs.phar
          standard: magento-coding-standard/Magento2/ruleset.xml
